from decouple import config

LOG_LEVEL = config("LOG_LEVEL", default="INFO")
OUTPUT_TABLE = config("OUTPUT_TABLE")
BRIGHTDATA_PROXY = config("BRIGHTDATA_PROXY")
BRIGHTDATA_PORT = config("BRIGHTDATA_PORT", cast=int)
BRIGHTDATA_USER = config("BRIGHTDATA_USER")
BRIGHTDATA_PASSWD = config("BRIGHTDATA_PASSWD")
MSSQL_AD_LOGIN = config("MSSQL_AD_LOGIN", cast=bool, default=False)
MSSQL_SERVER = config("MSSQL_SERVER")
MSSQL_DATABASE = config("MSSQL_DATABASE")

if not MSSQL_AD_LOGIN:
    MSSQL_USERNAME = config("MSSQL_USERNAME")
    MSSQL_PASSWORD = config("MSSQL_PASSWORD")
